### ISSUE TITLE
Class 'LogReader_Config' not found

### ISSUE THREAD

**Issue by soravmobi** [siloor/kohana-logreader#2] opened 2019-01-17 05:50 UTC
I am getting an error.

**Error [ 0 ]: Class 'LogReader_Config' not found**

Please let me know a possible solution.

**Comment by siloor** [comment] 2019-01-17 08:37
@soravmobi 

Are you sure, that you put the module into the right place? Also which version of Kohana are you using?

**Comment by soravmobi** [comment] 2019-01-17 08:52
@siloor  yes I put code inside modules directory. Please check the images.

Also, I enabled the module inside the bootstrap.php file.

**My Kohana version is: 3.2.2**

https://drive.google.com/file/d/1EZLkLi0zMMBR3bL5A747lSZfOynqpTMQ/view?usp=drivesdk

https://drive.google.com/file/d/1JBfXcYgElnglxVMzbR2YGVFOUotU6Iit/view?usp=drivesdk

Please check it.

**Comment by siloor** [comment] 2019-01-18 08:48
@soravmobi 

The problem is, that Kohana 3.2.2 is a very old version and it has a different autoloader. I tried to find a quick fix for this, but until now I didn't find a clean solution.

Also I suggest you to upgrade your Kohana version. 3.2.2 (2011 as I see) is a really old one and the migration shouldn't be that hard.

**Comment by soravmobi** [comment] 2019-01-18 10:09
Thanks for your reply.

Which Kohana version will support your kohana-loreader module?

**Comment by siloor** [comment] 2019-01-18 11:32
@soravmobi 

It should be everything above 3.3.0. Because the only problem is the changed autoloading mechanism.

**Comment by soravmobi** [comment] 2019-01-18 12:09
Ok, Thanks for your help !

**Closed as completed** 2019-01-18 12:10 UTC

**Comment by siloor** [comment] 2019-01-18 12:26
@soravmobi 

No problem, let me know if you need any further help!
